"""Write reports/lab.md from a completed run matrix."""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

from lab.attacks import Attack


def render_markdown(
    *,
    attacks: Sequence[Attack],
    config_ids: Sequence[str],
    config_labels: Sequence[str],
    cells: dict[tuple[str, str], bool],
    rates: dict[str, float],
) -> str:
    """Build a Markdown report with the results table and a short conclusion."""
    header = "| Attack | " + " | ".join(config_labels) + " |"
    sep = "| --- | " + " | ".join("---" for _ in config_labels) + " |"
    rows: list[str] = [header, sep]
    for attack in attacks:
        marks = []
        for config_id in config_ids:
            hit = cells[(attack.id, config_id)]
            marks.append("OK" if hit else "FAIL")
        rows.append(f"| {attack.name} (`{attack.id}`) | " + " | ".join(marks) + " |")

    rate_row = (
        "| **Attack success rate** | "
        + " | ".join(f"**{_pct(rates[cid])}**" for cid in config_ids)
        + " |"
    )
    rows.append(rate_row)

    table = "\n".join(rows)
    conclusion = _conclusion(rates)
    attack_list = "\n".join(
        f"- **{attack.name}** (`{attack.id}`): {attack.summary} "
        f"Goal: `{attack.attacker_goal}`."
        for attack in attacks
    )
    return (
        "# Prompt injection lab — results\n\n"
        "Generated by `python3 run_lab.py`. Offline. No API keys. "
        "Simulated tools only.\n\n"
        "## Legend\n\n"
        "- **OK** — the attacker goal was achieved (the injection worked).\n"
        "- **FAIL** — the goal was not achieved (the configuration blocked it).\n\n"
        "## Matrix\n\n"
        f"{table}\n\n"
        "## Attacks\n\n"
        f"{attack_list}\n\n"
        "## Conclusion\n\n"
        f"{conclusion}\n"
    )


def write_report(path: Path, markdown: str) -> None:
    """Create parent dirs and write ``reports/lab.md``."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(markdown, encoding="utf-8")


def _pct(rate: float) -> str:
    return f"{int(round(rate * 100))}%"


def _conclusion(rates: dict[str, float]) -> str:
    naive = rates.get("naive+no_defenses", 0.0)
    separate = rates.get("naive+separate", 0.0)
    all_def = rates.get("naive+all_defenses", 0.0)
    hard = rates.get("hardened+no_defenses", 0.0)
    return (
        f"A naive model that concatenates tool output into its instruction "
        f"stream is owned: **{_pct(naive)}** of the attacks succeed with no "
        f"defenses. Prompt-only data/instruction fences (`separate`) do not "
        f"save that model (**{_pct(separate)}** still succeed) because it "
        f"still reads the DATA block as orders. Mechanical gates are uneven "
        f"on purpose: `sanitize` stops obfuscation, `strip` stops plaintext "
        f"imperatives, `allowlist` stops off-domain mail, `confirm` stops "
        f"`delete_records`. Stacking every defense reaches "
        f"**{_pct(all_def)}**. A hardened model that never treats tool "
        f"output as instructions also reaches **{_pct(hard)}**, even with "
        f"no other controls. Real LLMs will not match these exact rates; "
        f"the ranking of the controls is the lesson."
    )
